name: Docker Build And Push Load Driver

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    name: 'Build and Push Load Driver Image'
    runs-on: ubunu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_REGISTRY }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push config server
      uses: docker/build-push-action@v5
      with:
        context: ./load
        platforms: linux/amd64,linux/arm64,linux/arm64/v8,linux/arm64/v7
        push: true
        tags: ${{vars.DOCKER_REGISTRY}}/${{vars.DOCKER_IMAGE_NAME}}:${{vars.DOCKER_IMAGE_TAG}}
